name = input("Ваше имя, фамилия?")
year = input("Ваша дата рождения")
learning = input("Где вы учитесь?")
print("Ваше имя, фамилия",name)
print('Ваша дата рождения' + str(year))
print ('вы учитесь в',learning)
